# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!

target 'TVShows' do
  pod 'Alamofire'
  pod 'CodableAlamofire'
  pod 'SVProgressHUD'
  pod 'Kingfisher'
  pod 'KWKeyboardListener'
end
